// <auto-generated />
namespace CLVSPOS.DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fields_sp_businesspartner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fields_sp_businesspartner));
        
        string IMigrationMetadata.Id
        {
            get { return "202008071557201_fields_sp_businesspartner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
