// <auto-generated />
namespace CLVSPOS.DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addColumn_CardsPinpad_table_PaydeskBalances : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumn_CardsPinpad_table_PaydeskBalances));
        
        string IMigrationMetadata.Id
        {
            get { return "202111101606020_addColumn_CardsPinpad_table_PaydeskBalances"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
