// <auto-generated />
namespace CLVSPOS.DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_Column_Description_Table_DBObjectNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Column_Description_Table_DBObjectNames));
        
        string IMigrationMetadata.Id
        {
            get { return "202111161937465_add_Column_Description_Table_DBObjectNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
